services:
  - type: web
    name: quick-learn
    region: singapore
    branch: main
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: /app/start.sh
    healthCheckPath: api/v1/health-check
    autoDeploy: true